// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5JfFqF6ZFx5Go6EQKle7bwldlevug5co',
    appId: '1:750841807226:web:a77b84fc98ffc613fe56c3',
    messagingSenderId: '750841807226',
    projectId: 'e-commerce12-9fde6',
    authDomain: 'e-commerce12-9fde6.firebaseapp.com',
    storageBucket: 'e-commerce12-9fde6.firebasestorage.app',
    measurementId: 'G-JR07LPQ1MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtpjnyl_KPNG65nuJNTLgXrtUH9griCas',
    appId: '1:750841807226:android:3bdf9079409f7b82fe56c3',
    messagingSenderId: '750841807226',
    projectId: 'e-commerce12-9fde6',
    storageBucket: 'e-commerce12-9fde6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxqXoliyaqumhp_eZcI8xxyC_uK7sqQ0k',
    appId: '1:750841807226:ios:595242fd65660429fe56c3',
    messagingSenderId: '750841807226',
    projectId: 'e-commerce12-9fde6',
    storageBucket: 'e-commerce12-9fde6.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxqXoliyaqumhp_eZcI8xxyC_uK7sqQ0k',
    appId: '1:750841807226:ios:595242fd65660429fe56c3',
    messagingSenderId: '750841807226',
    projectId: 'e-commerce12-9fde6',
    storageBucket: 'e-commerce12-9fde6.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5JfFqF6ZFx5Go6EQKle7bwldlevug5co',
    appId: '1:750841807226:web:332508305749cd3ffe56c3',
    messagingSenderId: '750841807226',
    projectId: 'e-commerce12-9fde6',
    authDomain: 'e-commerce12-9fde6.firebaseapp.com',
    storageBucket: 'e-commerce12-9fde6.firebasestorage.app',
    measurementId: 'G-9XM7SZCGF7',
  );
}
