// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';

import 'package:e_commerce_app/features/products/data/models/product_item_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    // registerAdapter(BrandModelAdapter());
    // registerAdapter(CategoryModelAdapter());
    registerAdapter(ProductItemModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    // registerAdapter(BrandModelAdapter());
    // registerAdapter(CategoryModelAdapter());
    registerAdapter(ProductItemModelAdapter());
  }
}
