// Mocks generated by Mockito 5.4.6 from annotations
// in e_commerce_app/test/helpers/mocks/mock_cart.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bloc/bloc.dart' as _i16;
import 'package:dartz/dartz.dart' as _i3;
import 'package:e_commerce_app/core/errors/failures/failures.dart' as _i9;
import 'package:e_commerce_app/core/params/params.dart' as _i7;
import 'package:e_commerce_app/features/cart/data/datasources/cart_data_source.dart'
    as _i5;
import 'package:e_commerce_app/features/cart/data/models/cart_response/cart_response.dart'
    as _i2;
import 'package:e_commerce_app/features/cart/domain/entities/cart.dart' as _i4;
import 'package:e_commerce_app/features/cart/domain/repositories/cart_repository.dart'
    as _i8;
import 'package:e_commerce_app/features/cart/domain/usecases/add_product_to_cart.dart'
    as _i11;
import 'package:e_commerce_app/features/cart/domain/usecases/delete_product_from_cart.dart'
    as _i12;
import 'package:e_commerce_app/features/cart/domain/usecases/get_cart.dart'
    as _i10;
import 'package:e_commerce_app/features/cart/domain/usecases/update_product_quantity.dart'
    as _i13;
import 'package:e_commerce_app/features/cart/presentation/manager/cart_bloc.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCartResponse_0 extends _i1.SmartFake implements _i2.CartResponse {
  _FakeCartResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCart_2 extends _i1.SmartFake implements _i4.Cart {
  _FakeCart_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CartDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartDataSource extends _i1.Mock implements _i5.CartDataSource {
  MockCartDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.CartResponse> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i6.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(this, Invocation.method(#getCart, [])),
            ),
          )
          as _i6.Future<_i2.CartResponse>);

  @override
  _i6.Future<_i2.CartResponse> deleteProduct({
    required _i7.CartParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [], {#params: params}),
            returnValue: _i6.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(
                this,
                Invocation.method(#deleteProduct, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i2.CartResponse>);

  @override
  _i6.Future<_i2.CartResponse> updateProduct({
    required _i7.CartParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [], {#params: params}),
            returnValue: _i6.Future<_i2.CartResponse>.value(
              _FakeCartResponse_0(
                this,
                Invocation.method(#updateProduct, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i2.CartResponse>);

  @override
  _i6.Future<void> addProduct({required _i7.CartParams? params}) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [], {#params: params}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i8.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>.value(
              _FakeEither_1<_i9.Failure, _i4.Cart>(
                this,
                Invocation.method(#getCart, []),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>);

  @override
  _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>> deleteProduct({
    required _i7.CartParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [], {#params: params}),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>.value(
              _FakeEither_1<_i9.Failure, _i4.Cart>(
                this,
                Invocation.method(#deleteProduct, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>);

  @override
  _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>> updateProduct({
    required _i7.CartParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [], {#params: params}),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>.value(
              _FakeEither_1<_i9.Failure, _i4.Cart>(
                this,
                Invocation.method(#updateProduct, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>);

  @override
  _i6.Future<_i3.Either<_i9.Failure, void>> addProduct({
    required _i7.CartParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [], {#params: params}),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, void>>.value(
              _FakeEither_1<_i9.Failure, void>(
                this,
                Invocation.method(#addProduct, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, void>>);
}

/// A class which mocks [GetCart].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCart extends _i1.Mock implements _i10.GetCart {
  MockGetCart() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>.value(
              _FakeEither_1<_i9.Failure, _i4.Cart>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>);
}

/// A class which mocks [AddProductToCart].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddProductToCart extends _i1.Mock implements _i11.AddProductToCart {
  MockAddProductToCart() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<_i9.Failure, void>> call({
    required _i7.CartParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, void>>.value(
              _FakeEither_1<_i9.Failure, void>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, void>>);
}

/// A class which mocks [DeleteProductFromCart].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteProductFromCart extends _i1.Mock
    implements _i12.DeleteProductFromCart {
  MockDeleteProductFromCart() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>> call({
    required _i7.CartParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>.value(
              _FakeEither_1<_i9.Failure, _i4.Cart>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>);
}

/// A class which mocks [UpdateProductQuantity].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProductQuantity extends _i1.Mock
    implements _i13.UpdateProductQuantity {
  MockUpdateProductQuantity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>> call({
    required _i7.CartParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>.value(
              _FakeEither_1<_i9.Failure, _i4.Cart>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, _i4.Cart>>);
}

/// A class which mocks [CartBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartBloc extends _i1.Mock implements _i14.CartBloc {
  MockCartBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Cart get cart =>
      (super.noSuchMethod(
            Invocation.getter(#cart),
            returnValue: _FakeCart_2(this, Invocation.getter(#cart)),
          )
          as _i4.Cart);

  @override
  set cart(_i4.Cart? value) => super.noSuchMethod(
    Invocation.setter(#cart, value),
    returnValueForMissingStub: null,
  );

  @override
  _i14.CartState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i15.dummyValue<_i14.CartState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i14.CartState);

  @override
  _i6.Stream<_i14.CartState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i14.CartState>.empty(),
          )
          as _i6.Stream<_i14.CartState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i14.CartEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i14.CartEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i14.CartState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i14.CartEvent>(
    _i16.EventHandler<E, _i14.CartState>? handler, {
    _i16.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i16.Transition<_i14.CartEvent, _i14.CartState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(_i14.CartEvent? event, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#onDone, [event, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i16.Change<_i14.CartState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
