// Mocks generated by Mockito 5.4.6 from annotations
// in e_commerce_app/test/helpers/mocks/mock_wishlist.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bloc/bloc.dart' as _i20;
import 'package:dartz/dartz.dart' as _i4;
import 'package:dio/dio.dart' as _i2;
import 'package:e_commerce_app/core/errors/failures/failures.dart' as _i13;
import 'package:e_commerce_app/core/network_handler/api_interface.dart' as _i5;
import 'package:e_commerce_app/core/network_handler/network_info.dart' as _i7;
import 'package:e_commerce_app/core/params/params.dart' as _i10;
import 'package:e_commerce_app/features/products/data/models/product_item_model.dart'
    as _i9;
import 'package:e_commerce_app/features/products/domain/entities/product_item.dart'
    as _i14;
import 'package:e_commerce_app/features/wishlist/data/datasources/wishlist_local_data_source.dart'
    as _i8;
import 'package:e_commerce_app/features/wishlist/data/datasources/wishlist_remote_data_source.dart'
    as _i11;
import 'package:e_commerce_app/features/wishlist/data/models/wishlist_response.dart'
    as _i3;
import 'package:e_commerce_app/features/wishlist/domain/repositories/wishlist_repository.dart'
    as _i12;
import 'package:e_commerce_app/features/wishlist/domain/usecases/add_product_to_wishlist.dart'
    as _i16;
import 'package:e_commerce_app/features/wishlist/domain/usecases/delete_product_from_wishlist.dart'
    as _i17;
import 'package:e_commerce_app/features/wishlist/domain/usecases/get_wishlist.dart'
    as _i15;
import 'package:e_commerce_app/features/wishlist/presentation/manager/wishlist_bloc.dart'
    as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWishlistResponse_1 extends _i1.SmartFake
    implements _i3.WishlistResponse {
  _FakeWishlistResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiInterface extends _i1.Mock implements _i5.ApiInterface {
  MockApiInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Response<dynamic>> get(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endPoint], {#queryParams: queryParams}),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [endPoint],
                  {#queryParams: queryParams},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> post(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> postFormData(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    _i2.FormData? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postFormData,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #postFormData,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> put(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> delete(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [WishlistLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWishlistLocalDataSource extends _i1.Mock
    implements _i8.WishlistLocalDataSource {
  MockWishlistLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i9.ProductItemModel>> getCachedWishlist() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedWishlist, []),
            returnValue: _i6.Future<List<_i9.ProductItemModel>>.value(
              <_i9.ProductItemModel>[],
            ),
          )
          as _i6.Future<List<_i9.ProductItemModel>>);

  @override
  _i6.Future<void> deleteCachedProduct({
    required _i10.WishlistParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCachedProduct, [], {#params: params}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addCachedProduct({
    required List<_i9.ProductItemModel>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addCachedProduct, [], {#items: items}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [WishlistRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWishlistRemoteDataSource extends _i1.Mock
    implements _i11.WishlistRemoteDataSource {
  MockWishlistRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.WishlistResponse> getWishlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWishlist, []),
            returnValue: _i6.Future<_i3.WishlistResponse>.value(
              _FakeWishlistResponse_1(
                this,
                Invocation.method(#getWishlist, []),
              ),
            ),
          )
          as _i6.Future<_i3.WishlistResponse>);

  @override
  _i6.Future<void> deleteProduct({required _i10.WishlistParams? params}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [], {#params: params}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addProduct({required _i10.WishlistParams? params}) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [], {#params: params}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [WishlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWishlistRepository extends _i1.Mock
    implements _i12.WishlistRepository {
  MockWishlistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i13.Failure, List<_i14.ProductItem>>> getWishlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWishlist, []),
            returnValue:
                _i6.Future<
                  _i4.Either<_i13.Failure, List<_i14.ProductItem>>
                >.value(
                  _FakeEither_2<_i13.Failure, List<_i14.ProductItem>>(
                    this,
                    Invocation.method(#getWishlist, []),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i13.Failure, List<_i14.ProductItem>>>);

  @override
  _i6.Future<_i4.Either<_i13.Failure, void>> deleteProduct({
    required _i10.WishlistParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [], {#params: params}),
            returnValue: _i6.Future<_i4.Either<_i13.Failure, void>>.value(
              _FakeEither_2<_i13.Failure, void>(
                this,
                Invocation.method(#deleteProduct, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i13.Failure, void>>);

  @override
  _i6.Future<_i4.Either<_i13.Failure, void>> addProduct({
    required _i10.WishlistParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [], {#params: params}),
            returnValue: _i6.Future<_i4.Either<_i13.Failure, void>>.value(
              _FakeEither_2<_i13.Failure, void>(
                this,
                Invocation.method(#addProduct, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i13.Failure, void>>);
}

/// A class which mocks [GetWishlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWishlist extends _i1.Mock implements _i15.GetWishlist {
  MockGetWishlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i13.Failure, List<_i14.ProductItem>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i6.Future<
                  _i4.Either<_i13.Failure, List<_i14.ProductItem>>
                >.value(
                  _FakeEither_2<_i13.Failure, List<_i14.ProductItem>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i13.Failure, List<_i14.ProductItem>>>);
}

/// A class which mocks [AddProductToWishlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddProductToWishlist extends _i1.Mock
    implements _i16.AddProductToWishlist {
  MockAddProductToWishlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i13.Failure, void>> call({
    required _i10.WishlistParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i6.Future<_i4.Either<_i13.Failure, void>>.value(
              _FakeEither_2<_i13.Failure, void>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i13.Failure, void>>);
}

/// A class which mocks [DeleteProductFromWishlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteProductFromWishlist extends _i1.Mock
    implements _i17.DeleteProductFromWishlist {
  MockDeleteProductFromWishlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i13.Failure, void>> call({
    required _i10.WishlistParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i6.Future<_i4.Either<_i13.Failure, void>>.value(
              _FakeEither_2<_i13.Failure, void>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i13.Failure, void>>);
}

/// A class which mocks [WishlistBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockWishlistBloc extends _i1.Mock implements _i18.WishlistBloc {
  MockWishlistBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i14.ProductItem> get wishlist =>
      (super.noSuchMethod(
            Invocation.getter(#wishlist),
            returnValue: <_i14.ProductItem>[],
          )
          as List<_i14.ProductItem>);

  @override
  set wishlist(List<_i14.ProductItem>? value) => super.noSuchMethod(
    Invocation.setter(#wishlist, value),
    returnValueForMissingStub: null,
  );

  @override
  _i18.WishlistState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i19.dummyValue<_i18.WishlistState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i18.WishlistState);

  @override
  _i6.Stream<_i18.WishlistState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i18.WishlistState>.empty(),
          )
          as _i6.Stream<_i18.WishlistState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i18.WishlistEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i18.WishlistEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i18.WishlistState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i18.WishlistEvent>(
    _i20.EventHandler<E, _i18.WishlistState>? handler, {
    _i20.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i20.Transition<_i18.WishlistEvent, _i18.WishlistState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i18.WishlistEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i20.Change<_i18.WishlistState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
