// Mocks generated by Mockito 5.4.6 from annotations
// in e_commerce_app/test/helpers/mocks/mock_product.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bloc/bloc.dart' as _i16;
import 'package:dartz/dartz.dart' as _i4;
import 'package:dio/dio.dart' as _i2;
import 'package:e_commerce_app/core/errors/failures/failures.dart' as _i11;
import 'package:e_commerce_app/core/network_handler/api_interface.dart' as _i5;
import 'package:e_commerce_app/core/network_handler/network_info.dart' as _i7;
import 'package:e_commerce_app/core/params/params.dart' as _i9;
import 'package:e_commerce_app/features/products/data/datasources/product_data_source.dart'
    as _i8;
import 'package:e_commerce_app/features/products/data/models/products_model.dart'
    as _i3;
import 'package:e_commerce_app/features/products/domain/entities/products.dart'
    as _i12;
import 'package:e_commerce_app/features/products/domain/repositories/product_repository.dart'
    as _i10;
import 'package:e_commerce_app/features/products/domain/usecases/get_products.dart'
    as _i13;
import 'package:e_commerce_app/features/products/presentation/manager/product_bloc.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsModel_1 extends _i1.SmartFake implements _i3.ProductsModel {
  _FakeProductsModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiInterface extends _i1.Mock implements _i5.ApiInterface {
  MockApiInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Response<dynamic>> get(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endPoint], {#queryParams: queryParams}),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [endPoint],
                  {#queryParams: queryParams},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> post(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> postFormData(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    _i2.FormData? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postFormData,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #postFormData,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> put(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> delete(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [ProductDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDataSource extends _i1.Mock implements _i8.ProductDataSource {
  MockProductDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.ProductsModel> getProducts({
    required _i9.ProductParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {#params: params}),
            returnValue: _i6.Future<_i3.ProductsModel>.value(
              _FakeProductsModel_1(
                this,
                Invocation.method(#getProducts, [], {#params: params}),
              ),
            ),
          )
          as _i6.Future<_i3.ProductsModel>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i10.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i11.Failure, _i12.Products>> getProducts({
    required _i9.ProductParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {#params: params}),
            returnValue:
                _i6.Future<_i4.Either<_i11.Failure, _i12.Products>>.value(
                  _FakeEither_2<_i11.Failure, _i12.Products>(
                    this,
                    Invocation.method(#getProducts, [], {#params: params}),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i11.Failure, _i12.Products>>);
}

/// A class which mocks [GetProducts].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProducts extends _i1.Mock implements _i13.GetProducts {
  MockGetProducts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i11.Failure, _i12.Products>> call({
    required _i9.ProductParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue:
                _i6.Future<_i4.Either<_i11.Failure, _i12.Products>>.value(
                  _FakeEither_2<_i11.Failure, _i12.Products>(
                    this,
                    Invocation.method(#call, [], {#params: params}),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i11.Failure, _i12.Products>>);
}

/// A class which mocks [ProductBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductBloc extends _i1.Mock implements _i14.ProductBloc {
  MockProductBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.ProductState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i15.dummyValue<_i14.ProductState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i14.ProductState);

  @override
  _i6.Stream<_i14.ProductState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i14.ProductState>.empty(),
          )
          as _i6.Stream<_i14.ProductState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i14.ProductEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i14.ProductEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i14.ProductState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i14.ProductEvent>(
    _i16.EventHandler<E, _i14.ProductState>? handler, {
    _i16.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i16.Transition<_i14.ProductEvent, _i14.ProductState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i14.ProductEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i16.Change<_i14.ProductState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
