// Mocks generated by Mockito 5.4.6 from annotations
// in e_commerce_app/test/helpers/mocks/mock_checkout.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:bloc/bloc.dart' as _i17;
import 'package:dartz/dartz.dart' as _i4;
import 'package:dio/dio.dart' as _i2;
import 'package:e_commerce_app/core/errors/failures/failures.dart' as _i12;
import 'package:e_commerce_app/core/handler/payment_handler/payment_interface_handler.dart'
    as _i7;
import 'package:e_commerce_app/core/params/params.dart' as _i10;
import 'package:e_commerce_app/features/checkout/data/datasources/payment_data_source.dart'
    as _i9;
import 'package:e_commerce_app/features/checkout/data/models/payment_model/payment_model.dart'
    as _i3;
import 'package:e_commerce_app/features/checkout/domain/entities/payment.dart'
    as _i13;
import 'package:e_commerce_app/features/checkout/domain/repositories/payment_repository.dart'
    as _i11;
import 'package:e_commerce_app/features/checkout/domain/usecases/create_payment_intent.dart'
    as _i14;
import 'package:e_commerce_app/features/checkout/presentation/manager/payment_bloc.dart'
    as _i15;
import 'package:flutter/foundation.dart' as _i5;
import 'package:flutter_stripe/flutter_stripe.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentModel_1 extends _i1.SmartFake implements _i3.PaymentModel {
  _FakePaymentModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueListenable_3<T> extends _i1.SmartFake
    implements _i5.ValueListenable<T> {
  _FakeValueListenable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlatformPayPaymentMethod_4 extends _i1.SmartFake
    implements _i6.PlatformPayPaymentMethod {
  _FakePlatformPayPaymentMethod_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSetupIntent_5 extends _i1.SmartFake implements _i6.SetupIntent {
  _FakeSetupIntent_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentIntent_6 extends _i1.SmartFake implements _i6.PaymentIntent {
  _FakePaymentIntent_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTokenData_7 extends _i1.SmartFake implements _i6.TokenData {
  _FakeTokenData_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentMethod_8 extends _i1.SmartFake implements _i6.PaymentMethod {
  _FakePaymentMethod_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRadarSession_9 extends _i1.SmartFake implements _i6.RadarSession {
  _FakeRadarSession_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddToWalletResult_10 extends _i1.SmartFake
    implements _i6.AddToWalletResult {
  _FakeAddToWalletResult_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCanAddCardToWalletResult_11 extends _i1.SmartFake
    implements _i6.CanAddCardToWalletResult {
  _FakeCanAddCardToWalletResult_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIsCardInWalletResult_12 extends _i1.SmartFake
    implements _i6.IsCardInWalletResult {
  _FakeIsCardInWalletResult_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFinancialConnectionTokenResult_13 extends _i1.SmartFake
    implements _i6.FinancialConnectionTokenResult {
  _FakeFinancialConnectionTokenResult_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeFinancialConnectionSessionResult_14 extends _i1.SmartFake
    implements _i6.FinancialConnectionSessionResult {
  _FakeFinancialConnectionSessionResult_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [PaymentInterfaceHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentInterfaceHandler extends _i1.Mock
    implements _i7.PaymentInterfaceHandler {
  MockPaymentInterfaceHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Response<dynamic>> get(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endPoint], {#queryParams: queryParams}),
            returnValue: _i8.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [endPoint],
                  {#queryParams: queryParams},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Response<dynamic>>);

  @override
  _i8.Future<_i2.Response<dynamic>> post(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i8.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Response<dynamic>>);

  @override
  _i8.Future<_i2.Response<dynamic>> postFormData(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    _i2.FormData? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postFormData,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i8.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #postFormData,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Response<dynamic>>);

  @override
  _i8.Future<_i2.Response<dynamic>> put(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i8.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Response<dynamic>>);

  @override
  _i8.Future<_i2.Response<dynamic>> delete(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i8.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [PaymentDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentDataSource extends _i1.Mock implements _i9.PaymentDataSource {
  MockPaymentDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.PaymentModel> createPaymentIntent({
    required _i10.PaymentParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPaymentIntent, [], {#params: params}),
            returnValue: _i8.Future<_i3.PaymentModel>.value(
              _FakePaymentModel_1(
                this,
                Invocation.method(#createPaymentIntent, [], {#params: params}),
              ),
            ),
          )
          as _i8.Future<_i3.PaymentModel>);
}

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i11.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.Either<_i12.Failure, _i13.Payment>> createPaymentIntent({
    required _i10.PaymentParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPaymentIntent, [], {#params: params}),
            returnValue:
                _i8.Future<_i4.Either<_i12.Failure, _i13.Payment>>.value(
                  _FakeEither_2<_i12.Failure, _i13.Payment>(
                    this,
                    Invocation.method(#createPaymentIntent, [], {
                      #params: params,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, _i13.Payment>>);
}

/// A class which mocks [CreatePaymentIntent].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreatePaymentIntent extends _i1.Mock
    implements _i14.CreatePaymentIntent {
  MockCreatePaymentIntent() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.Either<_i12.Failure, _i13.Payment>> call({
    required _i10.PaymentParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue:
                _i8.Future<_i4.Either<_i12.Failure, _i13.Payment>>.value(
                  _FakeEither_2<_i12.Failure, _i13.Payment>(
                    this,
                    Invocation.method(#call, [], {#params: params}),
                  ),
                ),
          )
          as _i8.Future<_i4.Either<_i12.Failure, _i13.Payment>>);
}

/// A class which mocks [PaymentBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentBloc extends _i1.Mock implements _i15.PaymentBloc {
  MockPaymentBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.PaymentState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i16.dummyValue<_i15.PaymentState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i15.PaymentState);

  @override
  _i8.Stream<_i15.PaymentState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i15.PaymentState>.empty(),
          )
          as _i8.Stream<_i15.PaymentState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i15.PaymentEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i15.PaymentEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i15.PaymentState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i15.PaymentEvent>(
    _i17.EventHandler<E, _i15.PaymentState>? handler, {
    _i17.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i17.Transition<_i15.PaymentEvent, _i15.PaymentState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i15.PaymentEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onChange(_i17.Change<_i15.PaymentState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Stripe].
///
/// See the documentation for Mockito's code generation for more information.
class MockStripe extends _i1.Mock implements _i6.Stripe {
  MockStripe() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ValueListenable<bool> get isPlatformPaySupportedListenable =>
      (super.noSuchMethod(
            Invocation.getter(#isPlatformPaySupportedListenable),
            returnValue: _FakeValueListenable_3<bool>(
              this,
              Invocation.getter(#isPlatformPaySupportedListenable),
            ),
          )
          as _i5.ValueListenable<bool>);

  @override
  bool get debugUpdatePlatformSheetCalled =>
      (super.noSuchMethod(
            Invocation.getter(#debugUpdatePlatformSheetCalled),
            returnValue: false,
          )
          as bool);

  @override
  bool get debugConfigurePlatformOrderTrackingCalled =>
      (super.noSuchMethod(
            Invocation.getter(#debugConfigurePlatformOrderTrackingCalled),
            returnValue: false,
          )
          as bool);

  @override
  set debugUpdatePlatformSheetCalled(bool? value) => super.noSuchMethod(
    Invocation.setter(#debugUpdatePlatformSheetCalled, value),
    returnValueForMissingStub: null,
  );

  @override
  set debugConfigurePlatformOrderTrackingCalled(bool? value) =>
      super.noSuchMethod(
        Invocation.setter(#debugConfigurePlatformOrderTrackingCalled, value),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> applySettings() =>
      (super.noSuchMethod(
            Invocation.method(#applySettings, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isPlatformPaySupported({
    _i6.IsGooglePaySupportedParams? googlePay,
    _i6.PlatformPayWebPaymentRequestCreateOptions?
    webPaymentRequestCreateOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isPlatformPaySupported, [], {
              #googlePay: googlePay,
              #webPaymentRequestCreateOptions: webPaymentRequestCreateOptions,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i6.PlatformPayPaymentMethod> createPlatformPayPaymentMethod({
    required _i6.PlatformPayPaymentMethodParams? params,
    bool? usesDeprecatedTokenFlow = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPlatformPayPaymentMethod, [], {
              #params: params,
              #usesDeprecatedTokenFlow: usesDeprecatedTokenFlow,
            }),
            returnValue: _i8.Future<_i6.PlatformPayPaymentMethod>.value(
              _FakePlatformPayPaymentMethod_4(
                this,
                Invocation.method(#createPlatformPayPaymentMethod, [], {
                  #params: params,
                  #usesDeprecatedTokenFlow: usesDeprecatedTokenFlow,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.PlatformPayPaymentMethod>);

  @override
  _i8.Future<_i6.SetupIntent> confirmPlatformPaySetupIntent({
    required String? clientSecret,
    required _i6.PlatformPayConfirmParams? confirmParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPlatformPaySetupIntent, [], {
              #clientSecret: clientSecret,
              #confirmParams: confirmParams,
            }),
            returnValue: _i8.Future<_i6.SetupIntent>.value(
              _FakeSetupIntent_5(
                this,
                Invocation.method(#confirmPlatformPaySetupIntent, [], {
                  #clientSecret: clientSecret,
                  #confirmParams: confirmParams,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.SetupIntent>);

  @override
  _i8.Future<_i6.PaymentIntent> confirmPlatformPayPaymentIntent({
    required String? clientSecret,
    required _i6.PlatformPayConfirmParams? confirmParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPlatformPayPaymentIntent, [], {
              #clientSecret: clientSecret,
              #confirmParams: confirmParams,
            }),
            returnValue: _i8.Future<_i6.PaymentIntent>.value(
              _FakePaymentIntent_6(
                this,
                Invocation.method(#confirmPlatformPayPaymentIntent, [], {
                  #clientSecret: clientSecret,
                  #confirmParams: confirmParams,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.PaymentIntent>);

  @override
  _i8.Future<void> updatePlatformSheet({
    required _i6.PlatformPaySheetUpdateParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlatformSheet, [], {#params: params}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> configurePlatformOrderTracking({
    required _i6.PlatformPayOrderDetails? orderDetails,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#configurePlatformOrderTracking, [], {
              #orderDetails: orderDetails,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.TokenData> createApplePayToken(
    Map<String, dynamic>? payment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createApplePayToken, [payment]),
            returnValue: _i8.Future<_i6.TokenData>.value(
              _FakeTokenData_7(
                this,
                Invocation.method(#createApplePayToken, [payment]),
              ),
            ),
          )
          as _i8.Future<_i6.TokenData>);

  @override
  _i8.Future<_i6.PaymentMethod> createPaymentMethod({
    required _i6.PaymentMethodParams? params,
    _i6.PaymentMethodOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPaymentMethod, [], {
              #params: params,
              #options: options,
            }),
            returnValue: _i8.Future<_i6.PaymentMethod>.value(
              _FakePaymentMethod_8(
                this,
                Invocation.method(#createPaymentMethod, [], {
                  #params: params,
                  #options: options,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.PaymentMethod>);

  @override
  _i8.Future<_i6.RadarSession> createRadarSession() =>
      (super.noSuchMethod(
            Invocation.method(#createRadarSession, []),
            returnValue: _i8.Future<_i6.RadarSession>.value(
              _FakeRadarSession_9(
                this,
                Invocation.method(#createRadarSession, []),
              ),
            ),
          )
          as _i8.Future<_i6.RadarSession>);

  @override
  _i8.Future<_i6.TokenData> createToken(_i6.CreateTokenParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#createToken, [params]),
            returnValue: _i8.Future<_i6.TokenData>.value(
              _FakeTokenData_7(this, Invocation.method(#createToken, [params])),
            ),
          )
          as _i8.Future<_i6.TokenData>);

  @override
  _i8.Future<_i6.PaymentIntent> retrievePaymentIntent(String? clientSecret) =>
      (super.noSuchMethod(
            Invocation.method(#retrievePaymentIntent, [clientSecret]),
            returnValue: _i8.Future<_i6.PaymentIntent>.value(
              _FakePaymentIntent_6(
                this,
                Invocation.method(#retrievePaymentIntent, [clientSecret]),
              ),
            ),
          )
          as _i8.Future<_i6.PaymentIntent>);

  @override
  _i8.Future<_i6.SetupIntent> retrieveSetupIntent(String? clientSecret) =>
      (super.noSuchMethod(
            Invocation.method(#retrieveSetupIntent, [clientSecret]),
            returnValue: _i8.Future<_i6.SetupIntent>.value(
              _FakeSetupIntent_5(
                this,
                Invocation.method(#retrieveSetupIntent, [clientSecret]),
              ),
            ),
          )
          as _i8.Future<_i6.SetupIntent>);

  @override
  _i8.Future<void> openApplePaySetup() =>
      (super.noSuchMethod(
            Invocation.method(#openApplePaySetup, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> handleURLCallback(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#handleURLCallback, [url]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i6.PaymentIntent> confirmPayment({
    required String? paymentIntentClientSecret,
    _i6.PaymentMethodParams? data,
    _i6.PaymentMethodOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPayment, [], {
              #paymentIntentClientSecret: paymentIntentClientSecret,
              #data: data,
              #options: options,
            }),
            returnValue: _i8.Future<_i6.PaymentIntent>.value(
              _FakePaymentIntent_6(
                this,
                Invocation.method(#confirmPayment, [], {
                  #paymentIntentClientSecret: paymentIntentClientSecret,
                  #data: data,
                  #options: options,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.PaymentIntent>);

  @override
  _i8.Future<_i6.PaymentIntent> handleNextAction(
    String? paymentIntentClientSecret, {
    String? returnURL,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #handleNextAction,
              [paymentIntentClientSecret],
              {#returnURL: returnURL},
            ),
            returnValue: _i8.Future<_i6.PaymentIntent>.value(
              _FakePaymentIntent_6(
                this,
                Invocation.method(
                  #handleNextAction,
                  [paymentIntentClientSecret],
                  {#returnURL: returnURL},
                ),
              ),
            ),
          )
          as _i8.Future<_i6.PaymentIntent>);

  @override
  _i8.Future<_i6.SetupIntent> handleNextActionForSetupIntent(
    String? setupIntentClientSecret, {
    String? returnURL,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #handleNextActionForSetupIntent,
              [setupIntentClientSecret],
              {#returnURL: returnURL},
            ),
            returnValue: _i8.Future<_i6.SetupIntent>.value(
              _FakeSetupIntent_5(
                this,
                Invocation.method(
                  #handleNextActionForSetupIntent,
                  [setupIntentClientSecret],
                  {#returnURL: returnURL},
                ),
              ),
            ),
          )
          as _i8.Future<_i6.SetupIntent>);

  @override
  _i8.Future<_i6.SetupIntent> confirmSetupIntent({
    required String? paymentIntentClientSecret,
    required _i6.PaymentMethodParams? params,
    _i6.PaymentMethodOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmSetupIntent, [], {
              #paymentIntentClientSecret: paymentIntentClientSecret,
              #params: params,
              #options: options,
            }),
            returnValue: _i8.Future<_i6.SetupIntent>.value(
              _FakeSetupIntent_5(
                this,
                Invocation.method(#confirmSetupIntent, [], {
                  #paymentIntentClientSecret: paymentIntentClientSecret,
                  #params: params,
                  #options: options,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.SetupIntent>);

  @override
  _i8.Future<String?> createTokenForCVCUpdate(String? cvc) =>
      (super.noSuchMethod(
            Invocation.method(#createTokenForCVCUpdate, [cvc]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<_i6.PaymentSheetPaymentOption?> initPaymentSheet({
    required _i6.SetupPaymentSheetParameters? paymentSheetParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initPaymentSheet, [], {
              #paymentSheetParameters: paymentSheetParameters,
            }),
            returnValue: _i8.Future<_i6.PaymentSheetPaymentOption?>.value(),
          )
          as _i8.Future<_i6.PaymentSheetPaymentOption?>);

  @override
  _i8.Future<_i6.PaymentSheetPaymentOption?> presentPaymentSheet({
    _i6.PaymentSheetPresentOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#presentPaymentSheet, [], {#options: options}),
            returnValue: _i8.Future<_i6.PaymentSheetPaymentOption?>.value(),
          )
          as _i8.Future<_i6.PaymentSheetPaymentOption?>);

  @override
  _i8.Future<void> intentCreationCallback(
    _i6.IntentCreationCallbackParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#intentCreationCallback, [params]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> confirmationTokenCreationCallback(
    _i6.IntentCreationCallbackParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmationTokenCreationCallback, [params]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> resetPaymentSheetCustomer() =>
      (super.noSuchMethod(
            Invocation.method(#resetPaymentSheetCustomer, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> confirmPaymentSheetPayment() =>
      (super.noSuchMethod(
            Invocation.method(#confirmPaymentSheetPayment, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> dangerouslyUpdateCardDetails(_i6.CardDetails? card) =>
      (super.noSuchMethod(
            Invocation.method(#dangerouslyUpdateCardDetails, [card]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> initGooglePay(_i6.GooglePayInitParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#initGooglePay, [params]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> presentGooglePay(_i6.PresentGooglePayParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#presentGooglePay, [params]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.PaymentMethod> createGooglePayPaymentMethod(
    _i6.CreateGooglePayPaymentParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createGooglePayPaymentMethod, [params]),
            returnValue: _i8.Future<_i6.PaymentMethod>.value(
              _FakePaymentMethod_8(
                this,
                Invocation.method(#createGooglePayPaymentMethod, [params]),
              ),
            ),
          )
          as _i8.Future<_i6.PaymentMethod>);

  @override
  _i8.Future<bool> isGooglePaySupported(
    _i6.IsGooglePaySupportedParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isGooglePaySupported, [params]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i6.PaymentIntent> collectBankAccount({
    required bool? isPaymentIntent,
    required String? clientSecret,
    required _i6.CollectBankAccountParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#collectBankAccount, [], {
              #isPaymentIntent: isPaymentIntent,
              #clientSecret: clientSecret,
              #params: params,
            }),
            returnValue: _i8.Future<_i6.PaymentIntent>.value(
              _FakePaymentIntent_6(
                this,
                Invocation.method(#collectBankAccount, [], {
                  #isPaymentIntent: isPaymentIntent,
                  #clientSecret: clientSecret,
                  #params: params,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.PaymentIntent>);

  @override
  _i8.Future<_i6.PaymentIntent> verifyPaymentIntentWithMicrodeposits({
    required bool? isPaymentIntent,
    required String? clientSecret,
    required _i6.VerifyMicroDepositsParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPaymentIntentWithMicrodeposits, [], {
              #isPaymentIntent: isPaymentIntent,
              #clientSecret: clientSecret,
              #params: params,
            }),
            returnValue: _i8.Future<_i6.PaymentIntent>.value(
              _FakePaymentIntent_6(
                this,
                Invocation.method(#verifyPaymentIntentWithMicrodeposits, [], {
                  #isPaymentIntent: isPaymentIntent,
                  #clientSecret: clientSecret,
                  #params: params,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.PaymentIntent>);

  @override
  _i8.Future<_i6.AddToWalletResult> canAddToWallet(String? last4) =>
      (super.noSuchMethod(
            Invocation.method(#canAddToWallet, [last4]),
            returnValue: _i8.Future<_i6.AddToWalletResult>.value(
              _FakeAddToWalletResult_10(
                this,
                Invocation.method(#canAddToWallet, [last4]),
              ),
            ),
          )
          as _i8.Future<_i6.AddToWalletResult>);

  @override
  _i8.Future<_i6.CanAddCardToWalletResult> canAddCardToWallet(
    _i6.CanAddCardToWalletParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#canAddCardToWallet, [params]),
            returnValue: _i8.Future<_i6.CanAddCardToWalletResult>.value(
              _FakeCanAddCardToWalletResult_11(
                this,
                Invocation.method(#canAddCardToWallet, [params]),
              ),
            ),
          )
          as _i8.Future<_i6.CanAddCardToWalletResult>);

  @override
  _i8.Future<_i6.IsCardInWalletResult> isCardInWallet(String? cardLastFour) =>
      (super.noSuchMethod(
            Invocation.method(#isCardInWallet, [cardLastFour]),
            returnValue: _i8.Future<_i6.IsCardInWalletResult>.value(
              _FakeIsCardInWalletResult_12(
                this,
                Invocation.method(#isCardInWallet, [cardLastFour]),
              ),
            ),
          )
          as _i8.Future<_i6.IsCardInWalletResult>);

  @override
  _i8.Future<_i6.FinancialConnectionTokenResult> collectBankAccountToken({
    required String? clientSecret,
    _i6.CollectBankAccountTokenParams? params =
        const _i6.CollectBankAccountTokenParams(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#collectBankAccountToken, [], {
              #clientSecret: clientSecret,
              #params: params,
            }),
            returnValue: _i8.Future<_i6.FinancialConnectionTokenResult>.value(
              _FakeFinancialConnectionTokenResult_13(
                this,
                Invocation.method(#collectBankAccountToken, [], {
                  #clientSecret: clientSecret,
                  #params: params,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.FinancialConnectionTokenResult>);

  @override
  _i8.Future<_i6.FinancialConnectionSessionResult>
  collectFinancialConnectionsAccounts({
    required String? clientSecret,
    _i6.CollectFinancialConnectionsAccountsParams? params =
        const _i6.CollectFinancialConnectionsAccountsParams(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#collectFinancialConnectionsAccounts, [], {
              #clientSecret: clientSecret,
              #params: params,
            }),
            returnValue: _i8.Future<_i6.FinancialConnectionSessionResult>.value(
              _FakeFinancialConnectionSessionResult_14(
                this,
                Invocation.method(#collectFinancialConnectionsAccounts, [], {
                  #clientSecret: clientSecret,
                  #params: params,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.FinancialConnectionSessionResult>);

  @override
  _i8.Future<List<String>> pollAndClearPendingStripeConnectUrls() =>
      (super.noSuchMethod(
            Invocation.method(#pollAndClearPendingStripeConnectUrls, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> initCustomerSheet({
    required _i6.CustomerSheetInitParams? customerSheetInitParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initCustomerSheet, [], {
              #customerSheetInitParams: customerSheetInitParams,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.CustomerSheetResult?> presentCustomerSheet({
    _i6.CustomerSheetPresentParams? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#presentCustomerSheet, [], {#options: options}),
            returnValue: _i8.Future<_i6.CustomerSheetResult?>.value(),
          )
          as _i8.Future<_i6.CustomerSheetResult?>);

  @override
  _i8.Future<_i6.CustomerSheetResult?>
  retrieveCustomerSheetPaymentOptionSelection() =>
      (super.noSuchMethod(
            Invocation.method(#retrieveCustomerSheetPaymentOptionSelection, []),
            returnValue: _i8.Future<_i6.CustomerSheetResult?>.value(),
          )
          as _i8.Future<_i6.CustomerSheetResult?>);

  @override
  void markNeedsSettings() => super.noSuchMethod(
    Invocation.method(#markNeedsSettings, []),
    returnValueForMissingStub: null,
  );
}
