// Mocks generated by Mockito 5.4.6 from annotations
// in e_commerce_app/test/helpers/mocks/mock_auth.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dartz/dartz.dart' as _i6;
import 'package:dio/dio.dart' as _i2;
import 'package:e_commerce_app/core/errors/failures/failures.dart' as _i17;
import 'package:e_commerce_app/core/handler/authentication_handler/auth_interface_handler.dart'
    as _i11;
import 'package:e_commerce_app/core/network_handler/api_interface.dart' as _i8;
import 'package:e_commerce_app/core/network_handler/network_info.dart' as _i10;
import 'package:e_commerce_app/core/params/params.dart' as _i15;
import 'package:e_commerce_app/core/services/profile_cached_service.dart'
    as _i30;
import 'package:e_commerce_app/features/authentication/data/datasources/authentication_data_source.dart'
    as _i14;
import 'package:e_commerce_app/features/authentication/data/models/address_model.dart'
    as _i4;
import 'package:e_commerce_app/features/authentication/data/models/authentication_user_model.dart'
    as _i3;
import 'package:e_commerce_app/features/authentication/data/models/user_google_response.dart'
    as _i5;
import 'package:e_commerce_app/features/authentication/domain/entities/address.dart'
    as _i19;
import 'package:e_commerce_app/features/authentication/domain/entities/profile.dart'
    as _i7;
import 'package:e_commerce_app/features/authentication/domain/entities/user.dart'
    as _i18;
import 'package:e_commerce_app/features/authentication/domain/entities/user_google.dart'
    as _i20;
import 'package:e_commerce_app/features/authentication/domain/repositories/authentication_repository.dart'
    as _i16;
import 'package:e_commerce_app/features/authentication/domain/usecases/add_address.dart'
    as _i26;
import 'package:e_commerce_app/features/authentication/domain/usecases/delete_address.dart'
    as _i27;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_forget_password.dart'
    as _i24;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_sign_in.dart'
    as _i22;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_sign_in_or_sign_up_with_google.dart'
    as _i25;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_sign_out.dart'
    as _i29;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_sign_up.dart'
    as _i23;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_update_data.dart'
    as _i28;
import 'package:e_commerce_app/features/authentication/presentation/manager/authentication_bloc.dart'
    as _i31;
import 'package:firebase_auth/firebase_auth.dart' as _i12;
import 'package:flutter/src/widgets/navigator.dart' as _i21;
import 'package:hydrated_bloc/hydrated_bloc.dart' as _i32;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthenticatedUserModel_1 extends _i1.SmartFake
    implements _i3.AuthenticatedUserModel {
  _FakeAuthenticatedUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddressModel_2 extends _i1.SmartFake implements _i4.AddressModel {
  _FakeAddressModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserGoogleResponse_3 extends _i1.SmartFake
    implements _i5.UserGoogleResponse {
  _FakeUserGoogleResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_4<L, R> extends _i1.SmartFake implements _i6.Either<L, R> {
  _FakeEither_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfile_5 extends _i1.SmartFake implements _i7.Profile {
  _FakeProfile_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiInterface extends _i1.Mock implements _i8.ApiInterface {
  MockApiInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Response<dynamic>> get(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endPoint], {#queryParams: queryParams}),
            returnValue: _i9.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [endPoint],
                  {#queryParams: queryParams},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response<dynamic>>);

  @override
  _i9.Future<_i2.Response<dynamic>> post(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i9.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response<dynamic>>);

  @override
  _i9.Future<_i2.Response<dynamic>> postFormData(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    _i2.FormData? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postFormData,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i9.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #postFormData,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response<dynamic>>);

  @override
  _i9.Future<_i2.Response<dynamic>> put(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i9.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response<dynamic>>);

  @override
  _i9.Future<_i2.Response<dynamic>> delete(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i9.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i10.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);
}

/// A class which mocks [AuthInterfaceHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthInterfaceHandler extends _i1.Mock
    implements _i11.AuthInterfaceHandler {
  MockAuthInterfaceHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);
}

/// A class which mocks [UserInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserInfo extends _i1.Mock implements _i12.UserInfo {
  MockUserInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get providerId =>
      (super.noSuchMethod(
            Invocation.getter(#providerId),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#providerId),
            ),
          )
          as String);
}

/// A class which mocks [AuthenticationDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationDataSource extends _i1.Mock
    implements _i14.AuthenticationDataSource {
  MockAuthenticationDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.AuthenticatedUserModel> signInWithCredentials({
    required _i15.SignInParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredentials, [], {#params: params}),
            returnValue: _i9.Future<_i3.AuthenticatedUserModel>.value(
              _FakeAuthenticatedUserModel_1(
                this,
                Invocation.method(#signInWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.AuthenticatedUserModel>);

  @override
  _i9.Future<_i3.AuthenticatedUserModel> signUpWithCredentials({
    required _i15.SignUpParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithCredentials, [], {#params: params}),
            returnValue: _i9.Future<_i3.AuthenticatedUserModel>.value(
              _FakeAuthenticatedUserModel_1(
                this,
                Invocation.method(#signUpWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.AuthenticatedUserModel>);

  @override
  _i9.Future<_i3.AuthenticatedUserModel> forgetPasswordWithCredentials({
    required _i15.ForgetPasswordParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPasswordWithCredentials, [], {
              #params: params,
            }),
            returnValue: _i9.Future<_i3.AuthenticatedUserModel>.value(
              _FakeAuthenticatedUserModel_1(
                this,
                Invocation.method(#forgetPasswordWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.AuthenticatedUserModel>);

  @override
  _i9.Future<_i3.AuthenticatedUserModel> updateUserData({
    required _i15.UserUpdateDataParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserData, [], {#params: params}),
            returnValue: _i9.Future<_i3.AuthenticatedUserModel>.value(
              _FakeAuthenticatedUserModel_1(
                this,
                Invocation.method(#updateUserData, [], {#params: params}),
              ),
            ),
          )
          as _i9.Future<_i3.AuthenticatedUserModel>);

  @override
  _i9.Future<_i4.AddressModel> addAddress({
    required _i15.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAddress, [], {#params: params}),
            returnValue: _i9.Future<_i4.AddressModel>.value(
              _FakeAddressModel_2(
                this,
                Invocation.method(#addAddress, [], {#params: params}),
              ),
            ),
          )
          as _i9.Future<_i4.AddressModel>);

  @override
  _i9.Future<void> deleteAddress({required _i15.AddressParams? params}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [], {#params: params}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i5.UserGoogleResponse> signInOrSignUpWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInOrSignUpWithGoogle, []),
            returnValue: _i9.Future<_i5.UserGoogleResponse>.value(
              _FakeUserGoogleResponse_3(
                this,
                Invocation.method(#signInOrSignUpWithGoogle, []),
              ),
            ),
          )
          as _i9.Future<_i5.UserGoogleResponse>);

  @override
  _i9.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i16.AuthenticationRepository {
  MockAuthenticationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Either<_i17.Failure, _i18.User>> signInWithCredentials({
    required _i15.SignInParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredentials, [], {#params: params}),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, _i18.User>>.value(
              _FakeEither_4<_i17.Failure, _i18.User>(
                this,
                Invocation.method(#signInWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, _i18.User>>);

  @override
  _i9.Future<_i6.Either<_i17.Failure, _i18.User>> signUpWithCredentials({
    required _i15.SignUpParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithCredentials, [], {#params: params}),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, _i18.User>>.value(
              _FakeEither_4<_i17.Failure, _i18.User>(
                this,
                Invocation.method(#signUpWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, _i18.User>>);

  @override
  _i9.Future<_i6.Either<_i17.Failure, void>> forgetPasswordWithCredentials({
    required _i15.ForgetPasswordParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPasswordWithCredentials, [], {
              #params: params,
            }),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, void>>.value(
              _FakeEither_4<_i17.Failure, void>(
                this,
                Invocation.method(#forgetPasswordWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, void>>);

  @override
  _i9.Future<_i6.Either<_i17.Failure, _i18.User>> updateUserData({
    required _i15.UserUpdateDataParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserData, [], {#params: params}),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, _i18.User>>.value(
              _FakeEither_4<_i17.Failure, _i18.User>(
                this,
                Invocation.method(#updateUserData, [], {#params: params}),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, _i18.User>>);

  @override
  _i9.Future<_i6.Either<_i17.Failure, _i19.Address>> addAddress({
    required _i15.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAddress, [], {#params: params}),
            returnValue:
                _i9.Future<_i6.Either<_i17.Failure, _i19.Address>>.value(
                  _FakeEither_4<_i17.Failure, _i19.Address>(
                    this,
                    Invocation.method(#addAddress, [], {#params: params}),
                  ),
                ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, _i19.Address>>);

  @override
  _i9.Future<_i6.Either<_i17.Failure, void>> deleteAddress({
    required _i15.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [], {#params: params}),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, void>>.value(
              _FakeEither_4<_i17.Failure, void>(
                this,
                Invocation.method(#deleteAddress, [], {#params: params}),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, void>>);

  @override
  _i9.Future<_i6.Either<_i17.Failure, _i20.UserGoogle>>
  signInOrSignUpWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInOrSignUpWithGoogle, []),
            returnValue:
                _i9.Future<_i6.Either<_i17.Failure, _i20.UserGoogle>>.value(
                  _FakeEither_4<_i17.Failure, _i20.UserGoogle>(
                    this,
                    Invocation.method(#signInOrSignUpWithGoogle, []),
                  ),
                ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, _i20.UserGoogle>>);

  @override
  _i9.Future<_i6.Either<_i17.Failure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, void>>.value(
              _FakeEither_4<_i17.Failure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, void>>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i21.NavigatorObserver {
  MockNavigatorObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void didPush(
    _i21.Route<dynamic>? route,
    _i21.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didPush, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didPop(_i21.Route<dynamic>? route, _i21.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i21.Route<dynamic>? route,
    _i21.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i21.Route<dynamic>? newRoute,
    _i21.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i21.Route<dynamic>? topRoute,
    _i21.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i21.Route<dynamic>? route,
    _i21.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSignIn extends _i1.Mock implements _i22.UserSignIn {
  MockUserSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Either<_i17.Failure, _i18.User>> call({
    required _i15.SignInParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, _i18.User>>.value(
              _FakeEither_4<_i17.Failure, _i18.User>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, _i18.User>>);
}

/// A class which mocks [UserSignUp].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSignUp extends _i1.Mock implements _i23.UserSignUp {
  MockUserSignUp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Either<_i17.Failure, _i18.User>> call({
    required _i15.SignUpParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, _i18.User>>.value(
              _FakeEither_4<_i17.Failure, _i18.User>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, _i18.User>>);
}

/// A class which mocks [UserForgetPassword].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserForgetPassword extends _i1.Mock
    implements _i24.UserForgetPassword {
  MockUserForgetPassword() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Either<_i17.Failure, void>> call({
    required _i15.ForgetPasswordParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, void>>.value(
              _FakeEither_4<_i17.Failure, void>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, void>>);
}

/// A class which mocks [UserSignInOrSignUpWithGoogle].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSignInOrSignUpWithGoogle extends _i1.Mock
    implements _i25.UserSignInOrSignUpWithGoogle {
  MockUserSignInOrSignUpWithGoogle() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Either<_i17.Failure, _i20.UserGoogle>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i9.Future<_i6.Either<_i17.Failure, _i20.UserGoogle>>.value(
                  _FakeEither_4<_i17.Failure, _i20.UserGoogle>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, _i20.UserGoogle>>);
}

/// A class which mocks [AddAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddAddress extends _i1.Mock implements _i26.AddAddress {
  MockAddAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Either<_i17.Failure, _i19.Address>> call({
    required _i15.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue:
                _i9.Future<_i6.Either<_i17.Failure, _i19.Address>>.value(
                  _FakeEither_4<_i17.Failure, _i19.Address>(
                    this,
                    Invocation.method(#call, [], {#params: params}),
                  ),
                ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, _i19.Address>>);
}

/// A class which mocks [DeleteAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAddress extends _i1.Mock implements _i27.DeleteAddress {
  MockDeleteAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Either<_i17.Failure, void>> call({
    required _i15.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, void>>.value(
              _FakeEither_4<_i17.Failure, void>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, void>>);
}

/// A class which mocks [UserUpdateData].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserUpdateData extends _i1.Mock implements _i28.UserUpdateData {
  MockUserUpdateData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Either<_i17.Failure, _i18.User>> call({
    required _i15.UserUpdateDataParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, _i18.User>>.value(
              _FakeEither_4<_i17.Failure, _i18.User>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, _i18.User>>);
}

/// A class which mocks [UserSignOut].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSignOut extends _i1.Mock implements _i29.UserSignOut {
  MockUserSignOut() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Either<_i17.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i9.Future<_i6.Either<_i17.Failure, void>>.value(
              _FakeEither_4<_i17.Failure, void>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i9.Future<_i6.Either<_i17.Failure, void>>);
}

/// A class which mocks [ProfileCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileCacheService extends _i1.Mock
    implements _i30.ProfileCacheService {
  MockProfileCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.Profile?> getCachedProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProfile, []),
            returnValue: _i9.Future<_i7.Profile?>.value(),
          )
          as _i9.Future<_i7.Profile?>);

  @override
  _i9.Future<void> saveData({required _i7.Profile? profile}) =>
      (super.noSuchMethod(
            Invocation.method(#saveData, [], {#profile: profile}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearField({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#clearField, [], {#key: key}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [AuthenticationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationBloc extends _i1.Mock
    implements _i31.AuthenticationBloc {
  MockAuthenticationBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Profile get profile =>
      (super.noSuchMethod(
            Invocation.getter(#profile),
            returnValue: _FakeProfile_5(this, Invocation.getter(#profile)),
          )
          as _i7.Profile);

  @override
  bool get isSignIn =>
      (super.noSuchMethod(Invocation.getter(#isSignIn), returnValue: false)
          as bool);

  @override
  set profile(_i7.Profile? value) => super.noSuchMethod(
    Invocation.setter(#profile, value),
    returnValueForMissingStub: null,
  );

  @override
  set isSignIn(bool? value) => super.noSuchMethod(
    Invocation.setter(#isSignIn, value),
    returnValueForMissingStub: null,
  );

  @override
  _i31.AuthenticationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i13.dummyValue<_i31.AuthenticationState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i31.AuthenticationState);

  @override
  _i9.Stream<_i31.AuthenticationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i31.AuthenticationState>.empty(),
          )
          as _i9.Stream<_i31.AuthenticationState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i13.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get storagePrefix =>
      (super.noSuchMethod(
            Invocation.getter(#storagePrefix),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#storagePrefix),
            ),
          )
          as String);

  @override
  String get storageToken =>
      (super.noSuchMethod(
            Invocation.getter(#storageToken),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#storageToken),
            ),
          )
          as String);

  @override
  _i31.AuthenticationState? fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]))
          as _i31.AuthenticationState?);

  @override
  Map<String, dynamic>? toJson(_i31.AuthenticationState? state) =>
      (super.noSuchMethod(Invocation.method(#toJson, [state]))
          as Map<String, dynamic>?);

  @override
  void add(_i31.AuthenticationEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i31.AuthenticationEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i31.AuthenticationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i31.AuthenticationEvent>(
    _i32.EventHandler<E, _i31.AuthenticationState>? handler, {
    _i32.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i32.Transition<_i31.AuthenticationEvent, _i31.AuthenticationState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i31.AuthenticationEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void onChange(_i32.Change<_i31.AuthenticationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void hydrate({
    _i32.Storage? storage,
    _i32.OnHydrationError? onError = _i32.defaultOnHydrationError,
  }) => super.noSuchMethod(
    Invocation.method(#hydrate, [], {#storage: storage, #onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
