// Mocks generated by Mockito 5.4.6 from annotations
// in e_commerce_app/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dartz/dartz.dart' as _i6;
import 'package:dio/dio.dart' as _i2;
import 'package:e_commerce_app/core/errors/failures/failures.dart' as _i14;
import 'package:e_commerce_app/core/handler/authentication_handler/auth_interface_handler.dart'
    as _i10;
import 'package:e_commerce_app/core/network_handler/api_interface.dart' as _i7;
import 'package:e_commerce_app/core/network_handler/network_info.dart' as _i9;
import 'package:e_commerce_app/core/params/params.dart' as _i12;
import 'package:e_commerce_app/features/authentication/data/datasources/authentication_data_source.dart'
    as _i11;
import 'package:e_commerce_app/features/authentication/data/models/address_model.dart'
    as _i4;
import 'package:e_commerce_app/features/authentication/data/models/authentication_user_model.dart'
    as _i3;
import 'package:e_commerce_app/features/authentication/data/models/user_google_response.dart'
    as _i5;
import 'package:e_commerce_app/features/authentication/domain/entities/address.dart'
    as _i16;
import 'package:e_commerce_app/features/authentication/domain/entities/user.dart'
    as _i15;
import 'package:e_commerce_app/features/authentication/domain/entities/user_google.dart'
    as _i17;
import 'package:e_commerce_app/features/authentication/domain/repositories/authentication_repository.dart'
    as _i13;
import 'package:e_commerce_app/features/authentication/domain/usecases/add_address.dart'
    as _i22;
import 'package:e_commerce_app/features/authentication/domain/usecases/delete_address.dart'
    as _i23;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_forget_password.dart'
    as _i20;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_sign_in.dart'
    as _i18;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_sign_in_or_sign_up_with_google.dart'
    as _i21;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_sign_up.dart'
    as _i19;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_update_data.dart'
    as _i24;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthenticatedUserModel_1 extends _i1.SmartFake
    implements _i3.AuthenticatedUserModel {
  _FakeAuthenticatedUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddressModel_2 extends _i1.SmartFake implements _i4.AddressModel {
  _FakeAddressModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserGoogleResponse_3 extends _i1.SmartFake
    implements _i5.UserGoogleResponse {
  _FakeUserGoogleResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_4<L, R> extends _i1.SmartFake implements _i6.Either<L, R> {
  _FakeEither_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiInterface extends _i1.Mock implements _i7.ApiInterface {
  MockApiInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Response<dynamic>> get(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endPoint], {#queryParams: queryParams}),
            returnValue: _i8.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [endPoint],
                  {#queryParams: queryParams},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Response<dynamic>>);

  @override
  _i8.Future<_i2.Response<dynamic>> post(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i8.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Response<dynamic>>);

  @override
  _i8.Future<_i2.Response<dynamic>> postFormData(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    _i2.FormData? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postFormData,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i8.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #postFormData,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Response<dynamic>>);

  @override
  _i8.Future<_i2.Response<dynamic>> put(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i8.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Response<dynamic>>);

  @override
  _i8.Future<_i2.Response<dynamic>> delete(
    String? endPoint, {
    Map<String, dynamic>? queryParams,
    Map<String, dynamic>? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endPoint],
              {#queryParams: queryParams, #body: body},
            ),
            returnValue: _i8.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [endPoint],
                  {#queryParams: queryParams, #body: body},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i9.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [AuthInterfaceHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthInterfaceHandler extends _i1.Mock
    implements _i10.AuthInterfaceHandler {
  MockAuthInterfaceHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [AuthenticationDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationDataSource extends _i1.Mock
    implements _i11.AuthenticationDataSource {
  MockAuthenticationDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.AuthenticatedUserModel> signInWithCredentials({
    required _i12.SignInParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredentials, [], {#params: params}),
            returnValue: _i8.Future<_i3.AuthenticatedUserModel>.value(
              _FakeAuthenticatedUserModel_1(
                this,
                Invocation.method(#signInWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.AuthenticatedUserModel>);

  @override
  _i8.Future<_i3.AuthenticatedUserModel> signUpWithCredentials({
    required _i12.SignUpParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithCredentials, [], {#params: params}),
            returnValue: _i8.Future<_i3.AuthenticatedUserModel>.value(
              _FakeAuthenticatedUserModel_1(
                this,
                Invocation.method(#signUpWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.AuthenticatedUserModel>);

  @override
  _i8.Future<_i3.AuthenticatedUserModel> forgetPasswordWithCredentials({
    required _i12.ForgetPasswordParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPasswordWithCredentials, [], {
              #params: params,
            }),
            returnValue: _i8.Future<_i3.AuthenticatedUserModel>.value(
              _FakeAuthenticatedUserModel_1(
                this,
                Invocation.method(#forgetPasswordWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.AuthenticatedUserModel>);

  @override
  _i8.Future<_i3.AuthenticatedUserModel> updateUserData({
    required _i12.UserUpdateDataParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserData, [], {#params: params}),
            returnValue: _i8.Future<_i3.AuthenticatedUserModel>.value(
              _FakeAuthenticatedUserModel_1(
                this,
                Invocation.method(#updateUserData, [], {#params: params}),
              ),
            ),
          )
          as _i8.Future<_i3.AuthenticatedUserModel>);

  @override
  _i8.Future<_i4.AddressModel> addAddress({
    required _i12.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAddress, [], {#params: params}),
            returnValue: _i8.Future<_i4.AddressModel>.value(
              _FakeAddressModel_2(
                this,
                Invocation.method(#addAddress, [], {#params: params}),
              ),
            ),
          )
          as _i8.Future<_i4.AddressModel>);

  @override
  _i8.Future<void> deleteAddress({required _i12.AddressParams? params}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [], {#params: params}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.UserGoogleResponse> signInOrSignUpWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInOrSignUpWithGoogle, []),
            returnValue: _i8.Future<_i5.UserGoogleResponse>.value(
              _FakeUserGoogleResponse_3(
                this,
                Invocation.method(#signInOrSignUpWithGoogle, []),
              ),
            ),
          )
          as _i8.Future<_i5.UserGoogleResponse>);

  @override
  _i8.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i13.AuthenticationRepository {
  MockAuthenticationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Either<_i14.Failure, _i15.User>> signInWithCredentials({
    required _i12.SignInParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredentials, [], {#params: params}),
            returnValue: _i8.Future<_i6.Either<_i14.Failure, _i15.User>>.value(
              _FakeEither_4<_i14.Failure, _i15.User>(
                this,
                Invocation.method(#signInWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, _i15.User>>);

  @override
  _i8.Future<_i6.Either<_i14.Failure, _i15.User>> signUpWithCredentials({
    required _i12.SignUpParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithCredentials, [], {#params: params}),
            returnValue: _i8.Future<_i6.Either<_i14.Failure, _i15.User>>.value(
              _FakeEither_4<_i14.Failure, _i15.User>(
                this,
                Invocation.method(#signUpWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, _i15.User>>);

  @override
  _i8.Future<_i6.Either<_i14.Failure, void>> forgetPasswordWithCredentials({
    required _i12.ForgetPasswordParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPasswordWithCredentials, [], {
              #params: params,
            }),
            returnValue: _i8.Future<_i6.Either<_i14.Failure, void>>.value(
              _FakeEither_4<_i14.Failure, void>(
                this,
                Invocation.method(#forgetPasswordWithCredentials, [], {
                  #params: params,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, void>>);

  @override
  _i8.Future<_i6.Either<_i14.Failure, _i15.User>> updateUserData({
    required _i12.UserUpdateDataParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserData, [], {#params: params}),
            returnValue: _i8.Future<_i6.Either<_i14.Failure, _i15.User>>.value(
              _FakeEither_4<_i14.Failure, _i15.User>(
                this,
                Invocation.method(#updateUserData, [], {#params: params}),
              ),
            ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, _i15.User>>);

  @override
  _i8.Future<_i6.Either<_i14.Failure, _i16.Address>> addAddress({
    required _i12.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAddress, [], {#params: params}),
            returnValue:
                _i8.Future<_i6.Either<_i14.Failure, _i16.Address>>.value(
                  _FakeEither_4<_i14.Failure, _i16.Address>(
                    this,
                    Invocation.method(#addAddress, [], {#params: params}),
                  ),
                ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, _i16.Address>>);

  @override
  _i8.Future<_i6.Either<_i14.Failure, void>> deleteAddress({
    required _i12.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [], {#params: params}),
            returnValue: _i8.Future<_i6.Either<_i14.Failure, void>>.value(
              _FakeEither_4<_i14.Failure, void>(
                this,
                Invocation.method(#deleteAddress, [], {#params: params}),
              ),
            ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, void>>);

  @override
  _i8.Future<_i6.Either<_i14.Failure, _i17.UserGoogle>>
  signInOrSignUpWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInOrSignUpWithGoogle, []),
            returnValue:
                _i8.Future<_i6.Either<_i14.Failure, _i17.UserGoogle>>.value(
                  _FakeEither_4<_i14.Failure, _i17.UserGoogle>(
                    this,
                    Invocation.method(#signInOrSignUpWithGoogle, []),
                  ),
                ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, _i17.UserGoogle>>);

  @override
  _i8.Future<_i6.Either<_i14.Failure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i8.Future<_i6.Either<_i14.Failure, void>>.value(
              _FakeEither_4<_i14.Failure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, void>>);
}

/// A class which mocks [UserSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSignIn extends _i1.Mock implements _i18.UserSignIn {
  MockUserSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Either<_i14.Failure, _i15.User>> call({
    required _i12.SignInParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i8.Future<_i6.Either<_i14.Failure, _i15.User>>.value(
              _FakeEither_4<_i14.Failure, _i15.User>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, _i15.User>>);
}

/// A class which mocks [UserSignUp].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSignUp extends _i1.Mock implements _i19.UserSignUp {
  MockUserSignUp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Either<_i14.Failure, _i15.User>> call({
    required _i12.SignUpParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i8.Future<_i6.Either<_i14.Failure, _i15.User>>.value(
              _FakeEither_4<_i14.Failure, _i15.User>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, _i15.User>>);
}

/// A class which mocks [UserForgetPassword].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserForgetPassword extends _i1.Mock
    implements _i20.UserForgetPassword {
  MockUserForgetPassword() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Either<_i14.Failure, void>> call({
    required _i12.ForgetPasswordParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i8.Future<_i6.Either<_i14.Failure, void>>.value(
              _FakeEither_4<_i14.Failure, void>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, void>>);
}

/// A class which mocks [UserSignInOrSignUpWithGoogle].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSignInOrSignUpWithGoogle extends _i1.Mock
    implements _i21.UserSignInOrSignUpWithGoogle {
  MockUserSignInOrSignUpWithGoogle() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Either<_i14.Failure, _i17.UserGoogle>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i8.Future<_i6.Either<_i14.Failure, _i17.UserGoogle>>.value(
                  _FakeEither_4<_i14.Failure, _i17.UserGoogle>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, _i17.UserGoogle>>);
}

/// A class which mocks [AddAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddAddress extends _i1.Mock implements _i22.AddAddress {
  MockAddAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Either<_i14.Failure, _i16.Address>> call({
    required _i12.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue:
                _i8.Future<_i6.Either<_i14.Failure, _i16.Address>>.value(
                  _FakeEither_4<_i14.Failure, _i16.Address>(
                    this,
                    Invocation.method(#call, [], {#params: params}),
                  ),
                ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, _i16.Address>>);
}

/// A class which mocks [DeleteAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAddress extends _i1.Mock implements _i23.DeleteAddress {
  MockDeleteAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Either<_i14.Failure, void>> call({
    required _i12.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i8.Future<_i6.Either<_i14.Failure, void>>.value(
              _FakeEither_4<_i14.Failure, void>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, void>>);
}

/// A class which mocks [UserUpdateData].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserUpdateData extends _i1.Mock implements _i24.UserUpdateData {
  MockUserUpdateData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Either<_i14.Failure, _i15.User>> call({
    required _i12.UserUpdateDataParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i8.Future<_i6.Either<_i14.Failure, _i15.User>>.value(
              _FakeEither_4<_i14.Failure, _i15.User>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i8.Future<_i6.Either<_i14.Failure, _i15.User>>);
}
