// Mocks generated by Mockito 5.4.6 from annotations
// in e_commerce_app/test/helpers/test_injection.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:e_commerce_app/core/errors/failures/failure.dart' as _i6;
import 'package:e_commerce_app/core/params/params.dart' as _i8;
import 'package:e_commerce_app/features/authentication/domain/entities/address.dart'
    as _i15;
import 'package:e_commerce_app/features/authentication/domain/entities/profile.dart'
    as _i3;
import 'package:e_commerce_app/features/authentication/domain/entities/user.dart'
    as _i7;
import 'package:e_commerce_app/features/authentication/domain/entities/user_google.dart'
    as _i12;
import 'package:e_commerce_app/features/authentication/domain/usecases/add_address.dart'
    as _i14;
import 'package:e_commerce_app/features/authentication/domain/usecases/delete_address.dart'
    as _i13;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_forget_password.dart'
    as _i10;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_sign_in.dart'
    as _i4;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_sign_in_or_sign_up_with_google.dart'
    as _i11;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_sign_up.dart'
    as _i9;
import 'package:e_commerce_app/features/authentication/domain/usecases/user_update_data.dart'
    as _i16;
import 'package:e_commerce_app/features/authentication/presentation/manager/authentication_bloc.dart'
    as _i17;
import 'package:hydrated_bloc/hydrated_bloc.dart' as _i19;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfile_1 extends _i1.SmartFake implements _i3.Profile {
  _FakeProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSignIn extends _i1.Mock implements _i4.UserSignIn {
  MockUserSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.User>> call({
    required _i8.SignInParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, _i7.User>>.value(
              _FakeEither_0<_i6.Failure, _i7.User>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.User>>);
}

/// A class which mocks [UserSignUp].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSignUp extends _i1.Mock implements _i9.UserSignUp {
  MockUserSignUp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.User>> call({
    required _i8.SignUpParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, _i7.User>>.value(
              _FakeEither_0<_i6.Failure, _i7.User>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.User>>);
}

/// A class which mocks [UserForgetPassword].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserForgetPassword extends _i1.Mock
    implements _i10.UserForgetPassword {
  MockUserForgetPassword() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> call({
    required _i8.ForgetPasswordParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [UserSignInOrSignUpWithGoogle].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSignInOrSignUpWithGoogle extends _i1.Mock
    implements _i11.UserSignInOrSignUpWithGoogle {
  MockUserSignInOrSignUpWithGoogle() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i12.UserGoogle>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i12.UserGoogle>>.value(
                  _FakeEither_0<_i6.Failure, _i12.UserGoogle>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i12.UserGoogle>>);
}

/// A class which mocks [DeleteAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAddress extends _i1.Mock implements _i13.DeleteAddress {
  MockDeleteAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> call({
    required _i8.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, void>>);
}

/// A class which mocks [AddAddress].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddAddress extends _i1.Mock implements _i14.AddAddress {
  MockAddAddress() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i15.Address>> call({
    required _i8.AddressParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i15.Address>>.value(
                  _FakeEither_0<_i6.Failure, _i15.Address>(
                    this,
                    Invocation.method(#call, [], {#params: params}),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i15.Address>>);
}

/// A class which mocks [UserUpdateData].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserUpdateData extends _i1.Mock implements _i16.UserUpdateData {
  MockUserUpdateData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.User>> call({
    required _i8.UserUpdateDataParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, _i7.User>>.value(
              _FakeEither_0<_i6.Failure, _i7.User>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.User>>);
}

/// A class which mocks [AuthenticationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationBloc extends _i1.Mock
    implements _i17.AuthenticationBloc {
  MockAuthenticationBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Profile get profile =>
      (super.noSuchMethod(
            Invocation.getter(#profile),
            returnValue: _FakeProfile_1(this, Invocation.getter(#profile)),
          )
          as _i3.Profile);

  @override
  bool get isSignIn =>
      (super.noSuchMethod(Invocation.getter(#isSignIn), returnValue: false)
          as bool);

  @override
  set profile(_i3.Profile? value) => super.noSuchMethod(
    Invocation.setter(#profile, value),
    returnValueForMissingStub: null,
  );

  @override
  set isSignIn(bool? value) => super.noSuchMethod(
    Invocation.setter(#isSignIn, value),
    returnValueForMissingStub: null,
  );

  @override
  _i17.AuthenticationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i18.dummyValue<_i17.AuthenticationState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i17.AuthenticationState);

  @override
  _i5.Stream<_i17.AuthenticationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i17.AuthenticationState>.empty(),
          )
          as _i5.Stream<_i17.AuthenticationState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i18.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get storagePrefix =>
      (super.noSuchMethod(
            Invocation.getter(#storagePrefix),
            returnValue: _i18.dummyValue<String>(
              this,
              Invocation.getter(#storagePrefix),
            ),
          )
          as String);

  @override
  String get storageToken =>
      (super.noSuchMethod(
            Invocation.getter(#storageToken),
            returnValue: _i18.dummyValue<String>(
              this,
              Invocation.getter(#storageToken),
            ),
          )
          as String);

  @override
  _i17.AuthenticationState? fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]))
          as _i17.AuthenticationState?);

  @override
  Map<String, dynamic>? toJson(_i17.AuthenticationState? state) =>
      (super.noSuchMethod(Invocation.method(#toJson, [state]))
          as Map<String, dynamic>?);

  @override
  void add(_i17.AuthenticationEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i17.AuthenticationEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i17.AuthenticationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i17.AuthenticationEvent>(
    _i19.EventHandler<E, _i17.AuthenticationState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i19.Transition<_i17.AuthenticationEvent, _i17.AuthenticationState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i17.AuthenticationEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onChange(_i19.Change<_i17.AuthenticationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void hydrate({
    _i19.Storage? storage,
    _i19.OnHydrationError? onError = _i19.defaultOnHydrationError,
  }) => super.noSuchMethod(
    Invocation.method(#hydrate, [], {#storage: storage, #onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
